# Logging Config Template
# MIT License
#
# Copyright (c) 2021 WH-2099
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# how to use: logging.config.dictConfig()

version: 1 #必须，默认为1

#incremental: False     #启用后仅有部分设置会生效
#disable_existing_loggers: True

loggers:
    #name:
    #level: NOTSET
    #handlers: []
    #propagate: True
    #filters: []

root:
    #level: WARNING
    #handlers: []
    #filters: []

_handlers_file:
    filename: &_filename .log
    mode: &_mode "a"
    encoding: &_encoding utf-8
    delay: &_delay False
    #errors: &_errors None

handlers:
    CONSOLE:
        #输出到控制台
        #level:
        #formatter:
        #filters: []
        class: logging.StreamHandler
        #stream: sys.stderr
    FILE:
        #输出到文件
        #level:
        #formatter:
        #filters: []
        class: logging.FileHandler
        filename: *_filename
        mode: *_mode
        encoding: *_encoding
        delay: *_delay
        #errors: *_errors
    RFILE:
        #轮换日志，到指定大小自动切分
        #level:
        #formatter:
        #filters: []
        class: logging.handlers.RotatingFileHandler
        maxBytes: 10485760 #10MB
        backupCount: 2
        filename: *_filename
        mode: *_mode
        encoding: *_encoding
        delay: *_delay
        #errors: *_errors
    TRFILE:
        #时间轮换日志，到指定时间自动切分
        #level:
        #formatter:
        #filters: []
        class: logging.handlers.TimedRotatingFileHandler
        when: "H" #"S"秒 "M"分 "H"时 "D"天 "midnight" "W0"-"W6"工作日(0=星期一)
        interval: 12 #when*interval
        backupCount: 2
        filename: *_filename
        encoding: *_encoding
        delay: *_delay
        #errors: *_errors
        #utc: False

#filters:
#    filterName:
#        name: 要过滤的logger的名称

formatters:
    # %(asctime)s
    # %(funcName)s
    # %(levelname)s
    # %(message)s
    # %(name)s
    # %(module)s
    # %(filename)s
    # %(pathname)s
    # %(process)d
    # %(processName)s
    # %(thread)d
    # %(threadName)s
    ALL:
        format: "%(asctime)s@%(process)d-%(processName)s#%(thread)d-%(threadName)s#%(pathname)s#%(name)s-%(levelname)s#%(funcName)s-%(message)s"
    DEFAULT:
        format: "%(asctime)s @ %(threadName)s-%(filename)s # %(name)s-%(levelname)s-%(message)s"
    LESS:
        format: "%(asctime)s @ %(module)s - %(name)s - %(levelname)s - %(message)s"
    MORE:
        format: "%(asctime)s@%(process)d-%(thread)d-%(pathname)s#%(name)s-%(levelname)s#%(funcName)s-%(message)s"
